<?php

namespace Stacktracer\SymfonyBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('stacktracer');

        $treeBuilder->getRootNode()
            ->children()
                ->booleanNode('enabled')
                    ->defaultTrue()
                    ->info('Enable or disable tracing globally')
                ->end()
                ->arrayNode('exclude_patterns')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                    ->info('Regex patterns for paths to exclude from tracing')
                ->end()
                ->arrayNode('transport')
                    ->isRequired()
                    ->info('API transport configuration (required)')
                    ->children()
                        ->scalarNode('endpoint')
                            ->isRequired()
                            ->cannotBeEmpty()
                            ->info('API endpoint URL to send traces (e.g., https://api.stacktracer.io/v1/traces)')
                        ->end()
                        ->scalarNode('api_key')
                            ->isRequired()
                            ->cannotBeEmpty()
                            ->info('API key for authentication')
                        ->end()
                        ->integerNode('batch_size')
                            ->defaultValue(50)
                            ->min(1)
                            ->max(500)
                            ->info('Number of traces to batch before sending')
                        ->end()
                        ->integerNode('flush_interval_ms')
                            ->defaultValue(5000)
                            ->min(100)
                            ->info('Maximum time to wait before flushing batch (milliseconds)')
                        ->end()
                        ->integerNode('max_queue_size')
                            ->defaultValue(500)
                            ->min(50)
                            ->info('Maximum traces to queue (oldest dropped on overflow)')
                        ->end()
                        ->integerNode('timeout')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(30)
                            ->info('HTTP timeout in seconds')
                        ->end()
                        ->booleanNode('compress')
                            ->defaultTrue()
                            ->info('Gzip compress payloads over 1KB')
                        ->end()
                        ->integerNode('max_retries')
                            ->defaultValue(3)
                            ->min(0)
                            ->max(10)
                            ->info('Number of retry attempts on failure')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('capture')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('request')
                            ->defaultTrue()
                            ->info('Capture HTTP request traces')
                        ->end()
                        ->booleanNode('exception')
                            ->defaultTrue()
                            ->info('Capture exception traces')
                        ->end()
                        ->integerNode('exception_context_lines')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(50)
                            ->info('Number of lines of code to capture around the exception location')
                        ->end()
                        ->integerNode('stacktrace_context_lines')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(50)
                            ->info('Number of lines of code to capture for each stack trace frame')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('performance')
                    ->addDefaultsIfNotSet()
                    ->info('Performance optimization settings')
                    ->children()
                        ->floatNode('sample_rate')
                            ->defaultValue(1.0)
                            ->min(0.0)
                            ->max(1.0)
                            ->info('Percentage of requests to trace (0.0 to 1.0). Set to 0.1 for 10% sampling.')
                        ->end()
                        ->integerNode('max_stack_frames')
                            ->defaultValue(50)
                            ->min(5)
                            ->max(200)
                            ->info('Maximum number of stack frames to capture')
                        ->end()
                        ->booleanNode('capture_code_context')
                            ->defaultTrue()
                            ->info('Whether to capture code snippets')
                        ->end()
                        ->booleanNode('filter_vendor_frames')
                            ->defaultTrue()
                            ->info('Collapse consecutive vendor/framework stack frames')
                        ->end()
                        ->booleanNode('capture_request_headers')
                            ->defaultTrue()
                            ->info('Capture HTTP request headers')
                        ->end()
                        ->arrayNode('sensitive_keys')
                            ->scalarPrototype()->end()
                            ->defaultValue(['password', 'token', 'secret', 'api_key', 'authorization', 'cookie'])
                            ->info('Keys to redact from captured data')
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
