<?php

declare(strict_types=1);

namespace Stacktracer\SymfonyBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration definition for Stacktracer bundle.
 *
 * Defines the configuration tree structure for stacktracer.yaml with all available
 * options for transport, capturing, performance, and service identification.
 *
 * @author Stacktracer <hello@stacktracer.io>
 */
final class Configuration implements ConfigurationInterface
{
    /**
     * Builds and returns the configuration tree for the Stacktracer bundle.
     *
     * @return TreeBuilder The configuration tree builder
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('stacktracer');

        $treeBuilder->getRootNode()
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable or disable tracing globally')
            ->end()
            ->arrayNode('exclude_patterns')
            ->scalarPrototype()->end()
            ->defaultValue([])
            ->info('Regex patterns for paths to exclude from tracing')
            ->end()
            ->arrayNode('transport')
            ->isRequired()
            ->info('API transport configuration (required)')
            ->children()
            ->scalarNode('endpoint')
            ->isRequired()
            ->cannotBeEmpty()
            ->info('API endpoint URL to send traces (e.g., https://api.stacktracer.io/v1/traces)')
            ->end()
            ->scalarNode('api_key')
            ->isRequired()
            ->cannotBeEmpty()
            ->info('API key for authentication')
            ->end()
            ->integerNode('batch_size')
            ->defaultValue(50)
            ->min(1)
            ->max(500)
            ->info('Number of traces to batch before sending')
            ->end()
            ->integerNode('flush_interval_ms')
            ->defaultValue(5000)
            ->min(100)
            ->info('Maximum time to wait before flushing batch (milliseconds)')
            ->end()
            ->integerNode('max_queue_size')
            ->defaultValue(500)
            ->min(50)
            ->info('Maximum traces to queue (oldest dropped on overflow)')
            ->end()
            ->integerNode('timeout')
            ->defaultValue(5)
            ->min(1)
            ->max(30)
            ->info('HTTP timeout in seconds')
            ->end()
            ->booleanNode('compress')
            ->defaultTrue()
            ->info('Gzip compress payloads over 1KB')
            ->end()
            ->integerNode('max_retries')
            ->defaultValue(3)
            ->min(0)
            ->max(10)
            ->info('Number of retry attempts on failure')
            ->end()
            ->end()
            ->end()
            ->arrayNode('capture')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('request')
            ->defaultTrue()
            ->info('Capture HTTP request traces')
            ->end()
            ->booleanNode('exception')
            ->defaultTrue()
            ->info('Capture exception traces')
            ->end()
            ->integerNode('oom_memory_increase')
            ->defaultValue(5242880)
            ->min(0)
            ->info('Memory (bytes) to add when OOM detected to allow error reporting (default 5MB, 0 to disable)')
            ->end()
            ->booleanNode('spans')
            ->defaultFalse()
            ->info('Enable OTEL spans (paid feature). Logs, breadcrumbs, and exceptions are always captured.')
            ->end()
            ->integerNode('exception_context_lines')
            ->defaultValue(5)
            ->min(1)
            ->max(50)
            ->info('Number of lines of code to capture around the exception location')
            ->end()
            ->integerNode('stacktrace_context_lines')
            ->defaultValue(5)
            ->min(1)
            ->max(50)
            ->info('Number of lines of code to capture for each stack trace frame')
            ->end()
            ->end()
            ->end()
            ->arrayNode('performance')
            ->addDefaultsIfNotSet()
            ->info('Performance optimization settings')
            ->children()
            ->floatNode('sample_rate')
            ->defaultValue(1.0)
            ->min(0.0)
            ->max(1.0)
            ->info('Percentage of requests to trace (0.0 to 1.0). Set to 0.1 for 10% sampling.')
            ->end()
            ->integerNode('max_stack_frames')
            ->defaultValue(50)
            ->min(5)
            ->max(200)
            ->info('Maximum number of stack frames to capture')
            ->end()
            ->booleanNode('capture_code_context')
            ->defaultTrue()
            ->info('Whether to capture code snippets')
            ->end()
            ->booleanNode('filter_vendor_frames')
            ->defaultTrue()
            ->info('Collapse consecutive vendor/framework stack frames')
            ->end()
            ->booleanNode('capture_request_headers')
            ->defaultTrue()
            ->info('Capture HTTP request headers')
            ->end()
            ->arrayNode('sensitive_keys')
            ->scalarPrototype()->end()
            ->defaultValue(['password', 'token', 'secret', 'api_key', 'authorization', 'cookie'])
            ->info('Keys to redact from captured data')
            ->end()
            ->end()
            ->end()
            ->arrayNode('service')
            ->addDefaultsIfNotSet()
            ->info('Service identification for distributed tracing')
            ->children()
            ->scalarNode('name')
            ->defaultValue('app')
            ->info('Service name for OTEL tracing')
            ->end()
            ->scalarNode('version')
            ->defaultValue('1.0.0')
            ->info('Service version for OTEL tracing')
            ->end()
            ->end()
            ->end()
            ->arrayNode('logging')
            ->addDefaultsIfNotSet()
            ->info('Monolog integration settings')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable Monolog handler integration')
            ->end()
            ->scalarNode('level')
            ->defaultValue('debug')
            ->info('Minimum log level to capture')
            ->end()
            ->booleanNode('capture_context')
            ->defaultTrue()
            ->info('Capture log context data')
            ->end()
            ->arrayNode('exclude_channels')
            ->scalarPrototype()->end()
            ->defaultValue(['event', 'doctrine'])
            ->info('Log channels to exclude from capture')
            ->end()
            ->end()
            ->end()
            ->arrayNode('integrations')
            ->addDefaultsIfNotSet()
            ->info('SDK integrations for framework-specific tracing')
            ->children()
            ->arrayNode('doctrine')
            ->addDefaultsIfNotSet()
            ->info('Doctrine DBAL query tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable Doctrine query tracing')
            ->end()
            ->floatNode('slow_query_threshold')
            ->defaultValue(100.0)
            ->min(0.0)
            ->info('Threshold in ms for slow query detection')
            ->end()
            ->end()
            ->end()
            ->arrayNode('http_client')
            ->addDefaultsIfNotSet()
            ->info('Symfony HttpClient tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable HTTP client tracing')
            ->end()
            ->booleanNode('propagate_context')
            ->defaultTrue()
            ->info('Inject W3C traceparent headers')
            ->end()
            ->end()
            ->end()
            ->arrayNode('messenger')
            ->addDefaultsIfNotSet()
            ->info('Symfony Messenger tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable Messenger tracing')
            ->end()
            ->end()
            ->end()
            ->arrayNode('cache')
            ->addDefaultsIfNotSet()
            ->info('Symfony Cache tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable cache tracing')
            ->end()
            ->end()
            ->end()
            ->arrayNode('console')
            ->addDefaultsIfNotSet()
            ->info('Console command tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable console command tracing')
            ->end()
            ->end()
            ->end()
            ->arrayNode('form')
            ->addDefaultsIfNotSet()
            ->info('Symfony Form tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable form validation error tracking')
            ->end()
            ->end()
            ->end()
            ->arrayNode('security')
            ->addDefaultsIfNotSet()
            ->info('Symfony Security tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable security event tracking (login, logout, access denied)')
            ->end()
            ->end()
            ->end()
            ->arrayNode('mailer')
            ->addDefaultsIfNotSet()
            ->info('Symfony Mailer tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable email sending tracking')
            ->end()
            ->end()
            ->end()
            ->arrayNode('twig')
            ->addDefaultsIfNotSet()
            ->info('Twig template tracing')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable template render tracking')
            ->end()
            ->floatNode('slow_threshold')
            ->defaultValue(50.0)
            ->min(0.0)
            ->info('Threshold in ms for slow template detection')
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
